- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*PasswordAuthentication\s+'
    line: "PasswordAuthentication no"
    state: present
  notify:
    - Reload sshd

- name: Remove any extra "PasswordAuthentication" lines from sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*PasswordAuthentication\s+(?!no)'
    state: absent
  notify:
    - Reload sshd
