openvpn_client_config: "/{{ ansible_fqdn }}.ovpn"
openvpn_ipv6_subnet: "{{ ansible_default_ipv6.address | ipsubnet(ansible_default_ipv6.prefix) | ipsubnet(ansible_default_ipv6.prefix | int + 1, 1) }}"
openvpn_dev: "tun0"
openvpn_tls_key: "/etc/openvpn/myvpn.tlsauth"
openvpn_port: 8000
openvpn_cipher: "AES-128-GCM"
openvpn_ipv4_subnet: "10.8.0.0/24"
openvpn_proto: "udp"
