- name: "Move openvpn interface to trusted zone"
  ansible.posix.firewalld:
    interface: "{{ openvpn_dev }}"
    zone: trusted
    permanent: true
    state: enabled
  register: firewalld_ovpn_interface_moved

- name: /etc/firewalld/services/openvpn.xml
  template:
    src: openvpn.xml.j2
    dest: /etc/firewalld/services/openvpn.xml
  register: openvpn_firewalld

- service:
    name: firewalld
    state: reloaded
  when: firewalld_ovpn_interface_moved.changed or openvpn_firewalld.changed

- name: "Enable openvpn service in public zone"
  ansible.posix.firewalld:
    service: openvpn
    zone: public
    permanent: true
    immediate: true
    state: enabled

- name: "Masquerade for openvpn ipv4 subnet"
  ansible.posix.firewalld:
    zone: public
    permanent: true
    immediate: true
    state: enabled
    rich_rule: 'rule family=ipv4 source address={{ openvpn_ipv4_subnet }} masquerade'
