- package:
    name: shadowsocks-libev
    state: latest
  notify:
    - restart shadowsocks

- package:
    name: simple-obfs
    state: latest
  when: shadowsocks_obfs
  notify:
    - restart shadowsocks

- template:
    src: config.json.j2
    dest: /etc/shadowsocks-libev/config.json
  notify:
    - restart shadowsocks

- template:
    src: fail2ban-filter.conf.j2
    dest: /etc/fail2ban/filter.d/shadowsocks-libev.conf
  notify:
    - reload fail2ban

- template:
    src: fail2ban-jail.conf.j2
    dest: /etc/fail2ban/jail.d/shadowsocks-libev.conf
  notify:
    - reload fail2ban

- template:
    src: client.json.j2
    dest: /etc/shadowsocks-libev/client.json

- fetch:
    src: /etc/shadowsocks-libev/client.json
    dest: "./downloads"

- template:
    src: shadowsocks.xml.j2
    dest: /etc/firewalld/services/shadowsocks.xml
  register: shadowsocks_firewalld

- service:
    name: firewalld
    state: reloaded
  when: shadowsocks_firewalld.changed

- ansible.posix.firewalld:
    service: shadowsocks
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
