- sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/90-ip-forward.conf
  with_items:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.ipv6.conf.all.forwarding
      value: 1
