- template:
    src: kernel-pin-backport.j2
    dest: /etc/apt/preferences.d/linux-image-amd64-backports

- package:
    name:
      - linux-image-amd64
      - linux-headers-amd64
    state: latest
  register: kernel_installed

- when: kernel_installed.changed
  include_role:
    name: reboot
    tasks_from: now
